### ISSUE TITLE
Fail to build on Windows

### ISSUE THREAD

**Issue by maximih** [alexcrichton/ssh2-rs#14]
Hi

I am trying to build a binary which depends on `ssh2-rs` using cargo on Windows 7. I have msys64 installed and gcc 4.9.2-4.

Are there some instructions available on how to build on windows?

The error I get:

```
Build failed, waiting for other jobs to finish...
failed to run custom build command for `libssh2-sys v0.1.23`
Process didn't exit successfully: `C:\<edit>\target\debug\build\libssh2-sys-235a8bd8d34c9dc8\build-script-build` (exit code: 101)
--- stdout
running: "make" "-fGNUmakefile" "WITH_WINCNG=1" "WITH_ZLIB=1" "lib"
gcc -O2 -DNDEBUG -DLIBSSH2_WIN32  -fno-builtin -fno-strict-aliasing -Wall  -D_AMD64_ -DLIBSSH2_WINCNG -DLIBSSH2_HAVE_ZLIB -I../win32 -I../include -I../../zlib-1.2.8 -c ../src/channel.c -o release/channel.o
GNUmakefile:232: recipe for target 'release/channel.o' failed

--- stderr
In file included from /usr/include/cygwin/sys_time.h:13:0,
                 from /usr/include/sys/time.h:61,
                 from /usr/include/sys/_default_fcntl.h:196,
                 from /usr/include/sys/fcntl.h:3,
                 from /usr/include/fcntl.h:15,
                 from ../src/channel.c:45:
/usr/include/sys/select.h:31:5: error: conflicting types for ‘select’
 int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,
     ^
In file included from ../win32/libssh2_config.h:10:0,
                 from ../src/libssh2_priv.h:44,
                 from ../src/channel.c:41:
/usr/include/w32api/winsock2.h:995:34: note: previous declaration of ‘select’ was here
   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writefds,fd_set *exceptfds,const PTIMEVAL timeout);
                                  ^
make: *** [release/channel.o] Error 1
thread '<main>' panicked at 'command did not succeed, exited with: exit code: 2', C:\msys64\<edit>\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.1.23\build.rs:123
```

Thanks

**Comment by alexcrichton** [comment]
How is your MSYS2 environment set up? An error when compiling the native library is quite surprising!

**Comment by maximih** [comment]
Thanks for your reply. 

What exactly do you mean by _How is your MSYS2 environment set up?_

I have followed [these](https://github.com/rust-lang/rust#building-on-windows) instructions and additionally installed `gcc` using pacman.

**Comment by alexcrichton** [comment]
I think you may want to uninstall the `gcc` package as the `mingw-w64-i686-toolchain` package should come with those headers by default.

**Comment by maximih** [comment]
You have a point. I was missing the migw64 bin folder from `PATH` so the fix was to just `export PATH=$PATH:/mingw64/bin`.

Now the compilation goes on but it fails later on during build of pure rust code:

```
   Compiling ssh2 v0.2.7
C:\msys64\home\<edited>\.cargo\registry\src\github.com-1ecc6299db9ec823\ssh2-0.2.7\src\util.rs:40:26: 40:27 error: mismatched types:
 expected `&[u8]`,
    found `&str`
(expected slice,
    found str) [E0308]
C:\msys64\home\<edited>\.cargo\registry\src\github.com-1ecc6299db9ec823\ssh2-0.2.7\src\util.rs:40         Some(s) => check(s),
                                                                                                                          ^
C:\msys64\home\<edited>\.cargo\registry\src\github.com-1ecc6299db9ec823\ssh2-0.2.7\src\util.rs:41:17: 42:72 error: mismatched types:
 expected `core::result::Result<&[u8], error::Error>`,
    found `error::Error`
(expected enum `core::result::Result`,
    found struct `error::Error`) [E0308]
C:\msys64\home\<edited>\.cargo\registry\src\github.com-1ecc6299db9ec823\ssh2-0.2.7\src\util.rs:41         None => Error::new(raw::LIBSSH2_ERROR_INVAL,
C:\msys64\home\<edited>\.cargo\registry\src\github.com-1ecc6299db9ec823\ssh2-0.2.7\src\util.rs:42                            "only unicode paths on windows may be used"),
error: aborting due to 2 previous errors
Could not compile `ssh2`.
```

Any clue?

**Comment by alexcrichton** [comment]
Oh it looks like I fixed some compile errors some time ago but forgot to publish a new version, I've now done so and you should be good to go!

**Comment by maximih** [comment]
Thanks! That part works now but the build still fails at the end:

````
error: linking with `gcc` failed: exit code: 1
...
note: ld: cannot find -lz
```
I guess this error has nothing to do with ssh. Let me know if I should open a cargo or rust issue.

Thanks for your help!

**Comment by alexcrichton** [comment]
Can you gist the full logs of the build? You may not have the MSYS/MinGW `ld` in your `PATH` and the bundled `ld` may not be finding `libz.a`.

**Comment by maximih** [comment]
See below (I filtered out some names for privacy reasons).

It seems I am using `ld` from mingw:

```
  $ which ld
/mingw64/bin/ld
```

```
$ PATH=/mingw64/bin:/c/Program\ Files/Rust\ stable\ 1.0/bin OPENSSL_LIB_DIR=/c/OpenSSL-Win64 OPENSSL_INCLUDE_DIR=/c/OpenSSL-Win64/include cargo build --verbose
       Fresh ansi_term v0.6.1
       Fresh regex-syntax v0.1.2
       Fresh matches v0.1.2
       Fresh unicode-width v0.1.1
       Fresh pkg-config v0.3.4
       Fresh bitflags v0.1.1
       Fresh typeable v0.1.1
       Fresh libc v0.1.8
       Fresh gcc v0.3.6
       Fresh httparse v0.1.3
       Fresh lazy_static v0.1.11
       Fresh traitobject v0.0.1
       Fresh strsim v0.3.0
       Fresh unicase v0.1.0
       Fresh rustc-serialize v0.3.14
       Fresh regex v0.1.33
       Fresh num_cpus v0.2.6
       Fresh log v0.3.1
       Fresh url v0.2.35
       Fresh docopt v0.6.66
       Fresh env_logger v0.3.1
       Fresh mime v0.0.11
       Fresh tabwriter v0.1.18 (https://github.com/maximih/tabwriter.git#2d9d80af)
       Fresh libz-sys v0.1.3
       Fresh time v0.1.26
       Fresh openssl-sys v0.6.2
       Fresh libssh2-sys v0.1.25
       Fresh openssl v0.6.2
       Fresh ssh2 v0.2.8
       Fresh cookie v0.1.21
       Fresh <edited> v0.1.0 (file:///C:/_WORK_/projects/rust/<edited>)
       Fresh hyper v0.5.2
       Fresh <edited> v0.1.0 (file:///C:/_WORK_/projects/rust/<edited>)
       Fresh <edited> v0.0.1 (file:///C:/_WORK_/projects/rust/<edited>)
   Compiling <edited> v0.3.0 (file:///C:/_WORK_/projects/rust/<edited>)
     Running `rustc src\main.rs --crate-name <edited> --crate-type bin -g --out-dir C:\_WORK_\projects\rust\<edited>\target\debug --emit=dep-info,link -L dependency=C:\_WORK_\projects\rust\<edited>\target\debug -L dependency=C:\_WORK_\projects\rust\<edited>\target\debug\deps --extern ansi_term=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libansi_term-513d367853f01712.rlib --extern log=C:\_WORK_\projects\rust\<edited>\target\debug\deps\liblog-54cf393d3c69686f.rlib --extern regex=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libregex-bee3bd02b59b955b.rlib --extern strsim=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libstrsim-fb046b3f6ce0ea34.rlib --extern rustc_serialize=C:\_WORK_\projects\rust\<edited>\target\debug\deps\librustc_serialize-9ef26f158d5284e0.rlib --extern <edited>=C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-a65969702758e31c.rlib --extern <edited>=C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-3d24aef9724c83c6.rlib --extern <edited>=C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-05b619e73949ad15.rlib --extern tabwriter=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libtabwriter-5889121e548b93eb.rlib --extern docopt=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libdocopt-1d63074d49917d6f.rlib --extern env_logger=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libenv_logger-63352e48193fbb80.rlib -L native=C:\_WORK_\projects\rust\<edited>\target\debug\build\libssh2-sys-4edc1b7b6d8a6bc4\out/lib -L native=C:/OpenSSL-Win64 -L native=C:\_WORK_\projects\rust\<edited>\target\debug\build\openssl-sys-5040130ff99796a0\out -L native=C:\_WORK_\projects\rust\<edited>\target\debug\build\time-f08bec52f4924e95\out`
       Fresh <edited> v0.0.1 (file:///C:/_WORK_/projects/rust/<edited>)

error: linking with `gcc` failed: exit code: 1
note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-static-libgcc" "-m64" "-L" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib" "-o" "C:\_WORK_\projects\rust\<edited>\target\debug\<edited>.exe" "C:\_WORK_\projects\rust\<edited>\target\debug\<edited>.o" "-Wl,--gc-sections" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libenv_logger-63352e48193fbb80.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libansi_term-513d367853f01712.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-a65969702758e31c.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-05b619e73949ad15.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-3d24aef9724c83c6.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libdocopt-1d63074d49917d6f.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libstrsim-fb046b3f6ce0ea34.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libtabwriter-5889121e548b93eb.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libregex-bee3bd02b59b955b.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libregex_syntax-8db057a1d27b1529.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libunicode_width-468c348f27a79727.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libhyper-595d44f1fae15675.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libmime-e3d384f950d18291.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libcookie-ac7973d866daef44.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libtime-f08bec52f4924e95.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libtraitobject-dc1e70e5c4501fdd.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libhttparse-a22b71e5e0845e38.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libtypeable-e1c7f5ec8654ad3e.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libopenssl-a36d86f1beea2185.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\liblazy_static-7e1b752366784e2f.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\liburl-a4f53e129e04fc84.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libmatches-68db25b520030534.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\librustc_serialize-9ef26f158d5284e0.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libopenssl_sys-5040130ff99796a0.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libnum_cpus-d64cdaf0c78cf4e8.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libunicase-29c711cff0d04b16.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-74b24435fccae9ea.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libssh2-bd23e449370353c7.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\liblog-54cf393d3c69686f.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\liblibssh2_sys-4edc1b7b6d8a6bc4.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\libbitflags-518ea12e21428edd.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\liblibz_sys-c145b8b5c75fd5a3.rlib" "C:\_WORK_\projects\rust\<edited>\target\debug\deps\liblibc-2eda841eb12a3090.rlib" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libstd-4e7c5e5c.rlib" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libcollections-4e7c5e5c.rlib" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libunicode-4e7c5e5c.rlib" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\librand-4e7c5e5c.rlib" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\liballoc-4e7c5e5c.rlib" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\liblibc-4e7c5e5c.rlib" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libcore-4e7c5e5c.rlib" "-L" "C:\_WORK_\projects\rust\<edited>\target\debug" "-L" "C:\_WORK_\projects\rust\<edited>\target\debug\deps" "-L" "C:\_WORK_\projects\rust\<edited>\target\debug\build\libssh2-sys-4edc1b7b6d8a6bc4\out/lib" "-L" "C:/OpenSSL-Win64" "-L" "C:\_WORK_\projects\rust\<edited>\target\debug\build\openssl-sys-5040130ff99796a0\out" "-L" "C:\_WORK_\projects\rust\<edited>\target\debug\build\time-f08bec52f4924e95\out" "-L" "C:\Program Files\Rust stable 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib" "-L" "C:\_WORK_\projects\rust\<edited>\.rust\bin\x86_64-pc-windows-gnu" "-L" "C:\_WORK_\projects\rust\<edited>\bin\x86_64-pc-windows-gnu" "-Wl,--whole-archive" "-Wl,-Bstatic" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-leay32" "-lssl32" "-lws2_32" "-lbcrypt" "-lcrypt32" "-luser32" "-lz" "-lws2_32" "-luserenv" "-lcompiler-rt"
note: ld: cannot find -lz

error: aborting due to previous error
Could not compile `<edited>`.

Caused by:
  Process didn't exit successfully: `rustc src\main.rs --crate-name <edited> --crate-type bin -g --out-dir C:\_WORK_\projects\rust\<edited>\target\debug --emit=dep-info,link -L dependency=C:\_WORK_\projects\rust\<edited>\target\debug -L dependency=C:\_WORK_\projects\rust\<edited>\target\debug\deps --extern ansi_term=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libansi_term-513d367853f01712.rlib --extern log=C:\_WORK_\projects\rust\<edited>\target\debug\deps\liblog-54cf393d3c69686f.rlib --extern regex=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libregex-bee3bd02b59b955b.rlib --extern strsim=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libstrsim-fb046b3f6ce0ea34.rlib --extern rustc_serialize=C:\_WORK_\projects\rust\<edited>\target\debug\deps\librustc_serialize-9ef26f158d5284e0.rlib --extern <edited>=C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-a65969702758e31c.rlib --extern <edited>=C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-3d24aef9724c83c6.rlib --extern <edited>=C:\_WORK_\projects\rust\<edited>\target\debug\deps\lib<edited>-05b619e73949ad15.rlib --extern tabwriter=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libtabwriter-5889121e548b93eb.rlib --extern docopt=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libdocopt-1d63074d49917d6f.rlib --extern env_logger=C:\_WORK_\projects\rust\<edited>\target\debug\deps\libenv_logger-63352e48193fbb80.rlib -L native=C:\_WORK_\projects\rust\<edited>\target\debug\build\libssh2-sys-4edc1b7b6d8a6bc4\out/lib -L native=C:/OpenSSL-Win64 -L native=C:\_WORK_\projects\rust\<edited>\target\debug\build\openssl-sys-5040130ff99796a0\out -L native=C:\_WORK_\projects\rust\<edited>\target\debug\build\time-f08bec52f4924e95\out` (exit code: 101)

```
 
Thanks

**Comment by maximih** [comment]
It seems `libz.a` is not actually in the `build` directory:

```
<edited>@<edited> MSYS /c/_WORK_/projects/rust/<edited>/target/debug/build
$ ls -lRt libz-sys-c145b8b5c75fd5a3
libz-sys-c145b8b5c75fd5a3:
total 397
-rw-r--r-- 1 <edited> Domain Users     23 Jun  3 13:10 output
drwxr-xr-x 1 <edited> Domain Users      0 Jun  3 13:10 out
-rwxr-xr-x 1 <edited> Domain Users 403827 Jun  3 13:10 build-script-build.exe

libz-sys-c145b8b5c75fd5a3/out:
total 0
```

**Comment by alexcrichton** [comment]
Ah yes the problem here is that you're not using the system gcc you have installed. The linker you're using is the one that's bundled by default with the Rust distribution, but to pick up system libraries (like `libz.a`) you'll need to use the system linker. This can be acquired through the `mingw-w64-x86_64-gcc` package I believe.

If you have an existing MinGW installation I would recommend unchecking the "native platform tools" box of the Rust installer as having two lying around ends up leading to weird errors like this.

**Comment by maximih** [comment]
Yes! That was it.

I reinstalled Rust without `Linker and platform libraries` then the build was successful.

Shouldn't this behavior be documented somewhere? I can open an issue, but for which project? Cargo or Rust?

If you don't mind, I can also create a PR for the `ssh2-rs` README to add a chapter with instructions for Windows.

Thanks a lot for your help!

**Comment by alexcrichton** [comment]
Yes please feel free!
